name: Build and Upload Applications

on:
  push:
    branches:
      - main
    tags:
      - '*.*.*'

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build executable
      run: pyinstaller --onefile webby.py

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: webby_windows
        path: dist/webby.exe

  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build executable
      run: pyinstaller --onefile webby.py

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: webby_linux
        path: dist/webby

  create-release:
    needs: [build-windows, build-linux]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Extract version from tag
      id: extract_version
      run: echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

    - name: Generate Changelog
      id: generate_changelog
      run: |
        echo "## Changes" > release.md
        git log $(git describe --tags --abbrev=0 @^)..@ --pretty=format:"%h - %s (%an, %ad)" --date=short >> release.md

    - name: Create and Upload Release
      uses: ncipollo/release-action@v1
      with:
        name: Webby v${{ env.version }}
        tag: ${{ github.ref }}
        bodyFile: release.md
        artifacts: |
          dist/webby.exe
          dist/webby
        token: ${{ secrets.GITHUB_TOKEN }}
